#!/usr/bin/env python3
# Copyright (c) Facebook, Inc. and its affiliates. All Rights Reserved.

from typing import List, Optional

from ax.core.observation import ObservationData, ObservationFeatures
from ax.core.search_space import SearchSpace
from ax.core.types import TConfig
from ax.modelbridge.transforms.base import Transform


class OutOfDesign(Transform):
    """Replace out of design arms with empty parameter maps.

    Any arm which does not fall into the provided search space is considered
    as an out of design arm. This can occur if parameters are missing, or if
    values are outside of the search space.
    The most common out of design arm is the status quo arm, which may not
    be generated by the Ax models.
    Out of design arms will have their parameters replaced with empty maps,
    as a signal to the model to ignore the parameter values.

    Transform is done in-place.
    """

    def __init__(
        self,
        search_space: SearchSpace,
        observation_features: List[ObservationFeatures],
        observation_data: List[ObservationData],
        config: Optional[TConfig] = None,
    ) -> None:
        self.ood_arms: List[int] = []
        for i, obsf in enumerate(observation_features):
            if not search_space.check_membership(obsf.parameters):
                self.ood_arms.append(i)

    def transform_observation_features(
        self, observation_features: List[ObservationFeatures]
    ) -> List[ObservationFeatures]:
        # Wipe parameter values for out of design arms.
        for i, obsf in enumerate(observation_features):
            if i in self.ood_arms:
                obsf.parameters = {}
        return observation_features
