version: "2"

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.12"
  jobs:
    post_install:
      # Install latest botorch if not on a released version
      - |
        tag=$(eval "git name-rev --name-only --tags HEAD")
        if [ $tag = "undefined" ]; then
          pip install git+https://github.com/cornellius-gp/gpytorch.git
          pip install git+https://github.com/pytorch/botorch.git
        fi

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - dev

sphinx:
  configuration: sphinx/source/conf.py
