name: Bug Report
description: File a bug report.
labels: ["bug"]
title: "[Bug]: "
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to fill out a bug report. We strive to make Ax a useful and stable library for all our users.
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Provide a detailed description of the bug as well as the expected behavior.
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: Please provide a minimal, reproducible example of the unexpected behavior.
      description: Follow [these guidelines](https://stackoverflow.com/help/minimal-reproducible-example) for writing your example.
    validations:
      required: true
  - type: textarea
    id: traceback
    attributes:
      label: Please paste any relevant traceback/logs produced by the example provided.
      description: This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: input
    id: ax-version
    attributes:
      label: Ax Version
      description: What version of Ax are you using?
    validations:
      required: true
  - type: input
    id: python-version
    attributes:
      label: Python Version
      description: What version of Python are you using?
    validations:
      required: true
  - type: input
    id: os
    attributes:
      label: Operating System
      description: What operating system are you using?
    validations:
      required: true
  - type: textarea
    id: suggested-fix
    attributes:
      label: (Optional) Describe any potential fixes you've considered to the issue outlined above.
  - type: dropdown
    id: pull-request
    attributes:
      label: Pull Request
      description: Are you willing to open a pull request fixing the bug outlined in this issue? (See [Contributing to Ax](https://github.com/facebook/Ax/blob/main/CONTRIBUTING.md))
      options:
        - "Yes"
        - "No"
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow Ax's [Code of Conduct](https://github.com/facebook/Ax/blob/main/CODE_OF_CONDUCT.md).
      options:
        - label: I agree to follow Ax's Code of Conduct
          required: true
