#!/usr/bin/env python3
# Copyright (c) Facebook, Inc. and its affiliates.
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

TS_MIN_WEIGHT_ERROR = """
No arms generated by Thompson Sampling had weight > min_weight.
The minimum weight required is {min_weight:2.4}, and the
maximum weight of any arm generated is {max_weight:2.4}.
"""
